import { FoodDeal, Cafeteria } from './types';

export const PRIMARY_GREEN = '#4CAF50';
export const ACCENT_ORANGE = '#FF6F00';

export const INITIAL_CAFETERIAS: Cafeteria[] = [
  {
    id: 'cafe-1',
    name: 'The Green Deli',
    imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&q=80&w=800',
    location: 'North Block, Level 1',
    isOpen: true,
    rating: 4.8,
    busyLevel: 'Quiet'
  },
  {
    id: 'cafe-2',
    name: 'South Gate Bistro',
    imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&q=80&w=800',
    location: 'Student Union Hub',
    isOpen: true,
    rating: 4.5,
    busyLevel: 'Moderate'
  },
  {
    id: 'cafe-3',
    name: 'The Oven Hub',
    imageUrl: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&q=80&w=800',
    location: 'Engineering Plaza',
    isOpen: true,
    rating: 4.9,
    busyLevel: 'Busy'
  },
  {
    id: 'cafe-4',
    name: 'Spice Route',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=800',
    location: 'International Wing',
    isOpen: true,
    rating: 4.7,
    busyLevel: 'Moderate'
  },
  {
    id: 'cafe-5',
    name: 'Brew & Bite',
    imageUrl: 'https://images.unsplash.com/photo-1559925393-8be0ec41b59b?auto=format&fit=crop&q=80&w=800',
    location: 'Library Quad',
    isOpen: true,
    rating: 4.6,
    busyLevel: 'Quiet'
  }
];

export const INITIAL_DEALS: FoodDeal[] = [
  // 1. THE GREEN DELI (5 items)
  {
    id: 'gd-1',
    cafeteriaId: 'cafe-1',
    name: 'Rainbow Quinoa Bowl',
    description: 'Organic tricolor quinoa with massaged kale and lemon tahini.',
    ingredients: ['Quinoa', 'Kale', 'Sweet Potato', 'Tahini'],
    carbonSavedKg: 1.2,
    nutritionalInfo: { calories: 420, protein: '12g', carbs: '54g', fat: '14g' },
    originalPrice: 280,
    discountedPrice: 85,
    quantity: 4,
    timeLeftMinutes: 32,
    cafeteriaName: 'The Green Deli',
    distance: '0.3 km',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Veg', 'Gluten-Free']
  },
  {
    id: 'gd-2',
    cafeteriaId: 'cafe-1',
    name: 'Avocado Toast Box',
    description: 'Sourdough toast with chunky avocado and heirloom tomatoes.',
    ingredients: ['Sourdough', 'Avocado', 'Tomato'],
    carbonSavedKg: 0.9,
    nutritionalInfo: { calories: 310, protein: '8g', carbs: '38g', fat: '12g' },
    originalPrice: 180,
    discountedPrice: 55,
    quantity: 6,
    timeLeftMinutes: 45,
    cafeteriaName: 'The Green Deli',
    distance: '0.3 km',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Veg', 'Fresh']
  },
  {
    id: 'gd-3',
    cafeteriaId: 'cafe-1',
    name: 'Greek Mezze Plate',
    description: 'Hummus, feta cheese, and kalamata olives with warm pita.',
    ingredients: ['Hummus', 'Feta', 'Olives', 'Pita'],
    carbonSavedKg: 0.7,
    nutritionalInfo: { calories: 450, protein: '15g', carbs: '50g', fat: '22g' },
    originalPrice: 250,
    discountedPrice: 75,
    quantity: 3,
    timeLeftMinutes: 15,
    cafeteriaName: 'The Green Deli',
    distance: '0.3 km',
    imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Veg', 'High Protein']
  },
  {
    id: 'gd-4',
    cafeteriaId: 'cafe-1',
    name: 'Superfood Salad',
    description: 'Mixed greens with blueberries, walnuts, and balsamic glaze.',
    ingredients: ['Mixed Greens', 'Blueberries', 'Walnuts'],
    carbonSavedKg: 0.5,
    nutritionalInfo: { calories: 280, protein: '6g', carbs: '22g', fat: '18g' },
    originalPrice: 160,
    discountedPrice: 45,
    quantity: 5,
    timeLeftMinutes: 20,
    cafeteriaName: 'The Green Deli',
    distance: '0.3 km',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Veg', 'Antioxidant']
  },
  {
    id: 'gd-5',
    cafeteriaId: 'cafe-1',
    name: 'Zesty Grain Bowl',
    description: 'Farro and roasted peppers with a lime-cilantro drizzle.',
    ingredients: ['Farro', 'Roasted Peppers', 'Lime'],
    carbonSavedKg: 0.8,
    nutritionalInfo: { calories: 390, protein: '11g', carbs: '62g', fat: '10g' },
    originalPrice: 210,
    discountedPrice: 65,
    quantity: 2,
    timeLeftMinutes: 10,
    cafeteriaName: 'The Green Deli',
    distance: '0.3 km',
    imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Veg', 'Grains']
  },

  // 2. SOUTH GATE BISTRO (5 items)
  {
    id: 'sg-1',
    cafeteriaId: 'cafe-2',
    name: 'Gourmet Steak Wrap',
    description: 'Prime beef strips with chimichurri and grilled peppers.',
    ingredients: ['Beef', 'Chimichurri', 'Peppers'],
    carbonSavedKg: 2.5,
    nutritionalInfo: { calories: 520, protein: '32g', carbs: '38g', fat: '22g' },
    originalPrice: 380,
    discountedPrice: 120,
    quantity: 3,
    timeLeftMinutes: 40,
    cafeteriaName: 'South Gate Bistro',
    distance: '0.9 km',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Non-Veg', 'Gourmet']
  },
  {
    id: 'sg-2',
    cafeteriaId: 'cafe-2',
    name: 'Classic Club Sandwich',
    description: 'Triple decker with turkey, bacon, and herb mayo.',
    ingredients: ['Turkey', 'Bacon', 'Bread'],
    carbonSavedKg: 1.4,
    nutritionalInfo: { calories: 480, protein: '24g', carbs: '42g', fat: '26g' },
    originalPrice: 220,
    discountedPrice: 70,
    quantity: 4,
    timeLeftMinutes: 25,
    cafeteriaName: 'South Gate Bistro',
    distance: '0.9 km',
    imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Non-Veg', 'Classic']
  },
  {
    id: 'sg-3',
    cafeteriaId: 'cafe-2',
    name: 'Teriyaki Salmon Fillet',
    description: 'Atlantic salmon with glaze and sesame bok choy.',
    ingredients: ['Salmon', 'Teriyaki', 'Bok Choy'],
    carbonSavedKg: 1.8,
    nutritionalInfo: { calories: 440, protein: '34g', carbs: '12g', fat: '28g' },
    originalPrice: 420,
    discountedPrice: 145,
    quantity: 2,
    timeLeftMinutes: 15,
    cafeteriaName: 'South Gate Bistro',
    distance: '0.9 km',
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Non-Veg', 'Omega-3']
  },
  {
    id: 'sg-4',
    cafeteriaId: 'cafe-2',
    name: 'Buffalo Chicken Salad',
    description: 'Spicy chicken strips over crisp romaine and blue cheese.',
    ingredients: ['Chicken', 'Buffalo Sauce', 'Romaine'],
    carbonSavedKg: 1.2,
    nutritionalInfo: { calories: 410, protein: '28g', carbs: '14g', fat: '28g' },
    originalPrice: 260,
    discountedPrice: 85,
    quantity: 6,
    timeLeftMinutes: 50,
    cafeteriaName: 'South Gate Bistro',
    distance: '0.9 km',
    imageUrl: 'https://images.unsplash.com/photo-1546793665-c74683c3f38d?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Non-Veg', 'Spicy']
  },
  {
    id: 'sg-5',
    cafeteriaId: 'cafe-2',
    name: 'Mediterranean Wrap',
    description: 'Grilled veggies and halloumi in a spinach tortilla.',
    ingredients: ['Halloumi', 'Grilled Veggies', 'Tortilla'],
    carbonSavedKg: 0.9,
    nutritionalInfo: { calories: 370, protein: '14g', carbs: '42g', fat: '18g' },
    originalPrice: 210,
    discountedPrice: 60,
    quantity: 5,
    timeLeftMinutes: 30,
    cafeteriaName: 'South Gate Bistro',
    distance: '0.9 km',
    imageUrl: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Veg', 'Healthy']
  },

  // 3. THE OVEN HUB (5 items)
  {
    id: 'oh-1',
    cafeteriaId: 'cafe-3',
    name: 'Wild Mushroom Pizza',
    description: 'Truffle-infused base with forest mushrooms and thyme.',
    ingredients: ['Mushrooms', 'Truffle Oil', 'Mozzarella'],
    carbonSavedKg: 1.1,
    nutritionalInfo: { calories: 620, protein: '18g', carbs: '72g', fat: '28g' },
    originalPrice: 240,
    discountedPrice: 75,
    quantity: 7,
    timeLeftMinutes: 54,
    cafeteriaName: 'The Oven Hub',
    distance: '1.5 km',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Veg', 'Signature']
  },
  {
    id: 'oh-2',
    cafeteriaId: 'cafe-3',
    name: 'Pepperoni Flatbread',
    description: 'Thin crust with spicy pepperoni and fresh basil.',
    ingredients: ['Pepperoni', 'San Marzano Tomato', 'Basil'],
    carbonSavedKg: 1.5,
    nutritionalInfo: { calories: 580, protein: '22g', carbs: '64g', fat: '26g' },
    originalPrice: 210,
    discountedPrice: 65,
    quantity: 4,
    timeLeftMinutes: 20,
    cafeteriaName: 'The Oven Hub',
    distance: '1.5 km',
    imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbad80ad38?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Non-Veg', 'Wood Fired']
  },
  {
    id: 'oh-3',
    cafeteriaId: 'cafe-3',
    name: 'Garden Lasagna',
    description: 'Layers of fresh pasta, zucchini, and ricotta cream.',
    ingredients: ['Zucchini', 'Ricotta', 'Pasta'],
    carbonSavedKg: 0.8,
    nutritionalInfo: { calories: 510, protein: '16g', carbs: '58g', fat: '24g' },
    originalPrice: 280,
    discountedPrice: 90,
    quantity: 3,
    timeLeftMinutes: 15,
    cafeteriaName: 'The Oven Hub',
    distance: '1.5 km',
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Veg', 'Pasta']
  },
  {
    id: 'oh-4',
    cafeteriaId: 'cafe-3',
    name: 'Garlic Knots Basket',
    description: 'Six warm knots with herb butter and marinara.',
    ingredients: ['Dough', 'Garlic', 'Butter'],
    carbonSavedKg: 0.4,
    nutritionalInfo: { calories: 350, protein: '8g', carbs: '45g', fat: '15g' },
    originalPrice: 120,
    discountedPrice: 40,
    quantity: 10,
    timeLeftMinutes: 60,
    cafeteriaName: 'The Oven Hub',
    distance: '1.5 km',
    imageUrl: 'https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Veg', 'Side']
  },
  {
    id: 'oh-5',
    cafeteriaId: 'cafe-3',
    name: 'Roasted Veggie Calzone',
    description: 'Folded pizza with eggplant, peppers, and pesto.',
    ingredients: ['Eggplant', 'Pesto', 'Cheese'],
    carbonSavedKg: 0.9,
    nutritionalInfo: { calories: 590, protein: '14g', carbs: '68g', fat: '30g' },
    originalPrice: 230,
    discountedPrice: 70,
    quantity: 5,
    timeLeftMinutes: 45,
    cafeteriaName: 'The Oven Hub',
    distance: '1.5 km',
    imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Veg', 'Hearty']
  },

  // 4. SPICE ROUTE (5 items)
  {
    id: 'sr-1',
    cafeteriaId: 'cafe-4',
    name: 'Butter Chicken Thali',
    description: 'Tender chicken in creamy tomato sauce with naan.',
    ingredients: ['Chicken', 'Cream', 'Spices', 'Naan'],
    carbonSavedKg: 2.2,
    nutritionalInfo: { calories: 720, protein: '38g', carbs: '65g', fat: '35g' },
    originalPrice: 350,
    discountedPrice: 110,
    quantity: 5,
    timeLeftMinutes: 55,
    cafeteriaName: 'Spice Route',
    distance: '1.2 km',
    imageUrl: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Non-Veg', 'Spicy']
  },
  {
    id: 'sr-2',
    cafeteriaId: 'cafe-4',
    name: 'Paneer Tikka Box',
    description: 'Grilled cottage cheese with bell peppers and mint chutney.',
    ingredients: ['Paneer', 'Peppers', 'Mint'],
    carbonSavedKg: 1.1,
    nutritionalInfo: { calories: 480, protein: '22g', carbs: '18g', fat: '34g' },
    originalPrice: 280,
    discountedPrice: 90,
    quantity: 6,
    timeLeftMinutes: 40,
    cafeteriaName: 'Spice Route',
    distance: '1.2 km',
    imageUrl: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Veg', 'Tandoor']
  },
  {
    id: 'sr-3',
    cafeteriaId: 'cafe-4',
    name: 'Veggie Biryani',
    description: 'Fragrant basmati rice with seasonal veggies and saffron.',
    ingredients: ['Basmati', 'Veggies', 'Saffron'],
    carbonSavedKg: 0.9,
    nutritionalInfo: { calories: 550, protein: '14g', carbs: '82g', fat: '18g' },
    originalPrice: 240,
    discountedPrice: 75,
    quantity: 8,
    timeLeftMinutes: 30,
    cafeteriaName: 'Spice Route',
    distance: '1.2 km',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21bc4a4f8?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Veg', 'Classic']
  },
  {
    id: 'sr-4',
    cafeteriaId: 'cafe-4',
    name: 'Chana Masala Bowl',
    description: 'Spiced chickpeas with brown rice and pickled onions.',
    ingredients: ['Chickpeas', 'Brown Rice', 'Onions'],
    carbonSavedKg: 0.7,
    nutritionalInfo: { calories: 410, protein: '16g', carbs: '64g', fat: '12g' },
    originalPrice: 190,
    discountedPrice: 55,
    quantity: 4,
    timeLeftMinutes: 20,
    cafeteriaName: 'Spice Route',
    distance: '1.2 km',
    imageUrl: 'https://images.unsplash.com/photo-1545231027-63b3f1600758?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Veg', 'Fiber+']
  },
  {
    id: 'sr-5',
    cafeteriaId: 'cafe-4',
    name: 'Samosa Duo',
    description: 'Two crispy potato pastries with tangy tamarind dip.',
    ingredients: ['Potato', 'Pastry', 'Tamarind'],
    carbonSavedKg: 0.3,
    nutritionalInfo: { calories: 320, protein: '6g', carbs: '42g', fat: '14g' },
    originalPrice: 100,
    discountedPrice: 30,
    quantity: 12,
    timeLeftMinutes: 15,
    cafeteriaName: 'Spice Route',
    distance: '1.2 km',
    imageUrl: 'https://images.unsplash.com/photo-1601050633647-3f9bc67e2311?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Veg', 'Snack']
  },

  // 5. BREW & BITE (5 items)
  {
    id: 'bb-1',
    cafeteriaId: 'cafe-5',
    name: 'Pesto Caprese Panini',
    description: 'Toasted ciabatta with pesto, tomato, and fresh buffalo mozzarella.',
    ingredients: ['Ciabatta', 'Pesto', 'Mozzarella'],
    carbonSavedKg: 0.8,
    nutritionalInfo: { calories: 460, protein: '18g', carbs: '48g', fat: '22g' },
    originalPrice: 210,
    discountedPrice: 65,
    quantity: 4,
    timeLeftMinutes: 45,
    cafeteriaName: 'Brew & Bite',
    distance: '0.1 km',
    imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Veg', 'Artisanal']
  },
  {
    id: 'bb-2',
    cafeteriaId: 'cafe-5',
    name: 'Almond Croissant',
    description: 'Buttery, flakey pastry topped with sliced almonds.',
    ingredients: ['Pastry', 'Almonds', 'Butter'],
    carbonSavedKg: 0.4,
    nutritionalInfo: { calories: 340, protein: '7g', carbs: '36g', fat: '18g' },
    originalPrice: 150,
    discountedPrice: 45,
    quantity: 8,
    timeLeftMinutes: 60,
    cafeteriaName: 'Brew & Bite',
    distance: '0.1 km',
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Veg', 'Bakery']
  },
  {
    id: 'bb-3',
    cafeteriaId: 'cafe-5',
    name: 'Tuna Salad Croissant',
    description: 'Creamy tuna salad on a fresh-baked croissant.',
    ingredients: ['Tuna', 'Croissant', 'Mayo'],
    carbonSavedKg: 1.1,
    nutritionalInfo: { calories: 420, protein: '24g', carbs: '32g', fat: '22g' },
    originalPrice: 240,
    discountedPrice: 80,
    quantity: 3,
    timeLeftMinutes: 20,
    cafeteriaName: 'Brew & Bite',
    distance: '0.1 km',
    imageUrl: 'https://images.unsplash.com/photo-1550507992-eb63ffee0847?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Non-Veg', 'Lunch']
  },
  {
    id: 'bb-4',
    cafeteriaId: 'cafe-5',
    name: 'Blueberry Muffin Box',
    description: 'Set of two oversized fresh blueberry muffins.',
    ingredients: ['Blueberries', 'Flour', 'Sugar'],
    carbonSavedKg: 0.3,
    nutritionalInfo: { calories: 510, protein: '6g', carbs: '78g', fat: '18g' },
    originalPrice: 180,
    discountedPrice: 50,
    quantity: 5,
    timeLeftMinutes: 35,
    cafeteriaName: 'Brew & Bite',
    distance: '0.1 km',
    imageUrl: 'https://images.unsplash.com/photo-1558401391-7899b4bd5bbf?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Veg', 'Sweet']
  },
  {
    id: 'bb-5',
    cafeteriaId: 'cafe-5',
    name: 'Roast Beef Sandwich',
    description: 'Shaved roast beef with horseradish and arugula.',
    ingredients: ['Roast Beef', 'Horseradish', 'Arugula'],
    carbonSavedKg: 2.1,
    nutritionalInfo: { calories: 540, protein: '38g', carbs: '44g', fat: '24g' },
    originalPrice: 290,
    discountedPrice: 95,
    quantity: 2,
    timeLeftMinutes: 10,
    cafeteriaName: 'Brew & Bite',
    distance: '0.1 km',
    imageUrl: 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&q=80&w=800',
    isClaimed: false,
    tags: ['Non-Veg', 'Hearty']
  }
];
